# Generated by Django 5.1.5 on 2025-02-02 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductNumber', models.IntegerField(unique=True)),
                ('ProductDate', models.DateField()),
                ('DeptNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
    ]
