# Generated by Django 4.2.18 on 2025-02-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x200'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductNumber',
            field=models.IntegerField(),
        ),
    ]
